import {
  BlockQuote,
  Bold,
  Heading,
  Indent,
  Italic,
  Link,
  List,
  MediaEmbed,
  Paragraph,
  Alignment,
  AutoLink,
  Code,
  CodeBlock,
  Essentials,
  FindAndReplace,
  Font,
  Highlight,
  HorizontalLine,
  HtmlEmbed,
  ImageInsert,
  ImageResize,
  IndentBlock,
  GeneralHtmlSupport,
  ListProperties,
  TodoList,
  PageBreak,
  PasteFromOffice,
  PictureEditing,
  RemoveFormat,
  ShowBlocks,
  SourceEditing,
  SpecialCharacters,
  SpecialCharactersEssentials,
  Style,
  Strikethrough,
  Subscript,
  Superscript,
  TextTransformation,
  Underline,
  WordCount,
  ImageUpload,
  ClassicEditor,
} from "ckeditor5";
// import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import "ckeditor5/ckeditor5.css";

ClassicEditor.create(document.querySelector("#editor"), {
  plugins: [
    ImageUpload,
    BlockQuote,
    Bold,
    Heading,
    Indent,
    Italic,
    Link,
    List,
    MediaEmbed,
    Paragraph,
    Alignment,
    AutoLink,
    Code,
    CodeBlock,
    Essentials,
    FindAndReplace,
    Font,
    Highlight,
    HorizontalLine,
    HtmlEmbed,
    ImageInsert,
    ImageResize,
    IndentBlock,
    GeneralHtmlSupport,
    ListProperties,
    TodoList,
    PageBreak,
    PasteFromOffice,
    PictureEditing,
    RemoveFormat,
    ShowBlocks,
    SourceEditing,
    SpecialCharacters,
    SpecialCharactersEssentials,
    Style,
    Strikethrough,
    Subscript,
    Superscript,
    TextTransformation,
    Underline,
    WordCount,
  ],
  toolbar: ["heading", "|", "bold", "italic", "link"],
  licenseKey: "GPL",
})
  .then((editor) => {
    window.editor = editor; // 方便控制台调试
  })
  .catch((error) => {});
